In [1]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

In [3]:
df = pd.read_csv("house_prices_practice.csv")
df.head()

,Id,OverallQual,GrLivArea,GarageCars,TotalBsmtSF,YearBuilt,FullBath,BedroomAbvGr,LotArea,SalePrice
0,1,7,1560,0,1658,1969,2,1,8059,177106
1,2,4,2827,2,1319,2012,3,4,13530,301044
2,3,8,3920,0,841,2010,1,4,9010,360609
3,4,5,3044,0,1058,1998,0,4,13207,240556
4,5,7,801,1,2428,2020,0,1,9117,193656

In [4]:
print(df.head())
print(df.shape)
print(df.info())

   Id  OverallQual  GrLivArea  GarageCars  TotalBsmtSF  YearBuilt  FullBath  \
0   1            7       1560           0         1658       1969         2
1   2            4       2827           2         1319       2012         3
2   3            8       3920           0          841       2010         1
3   4            5       3044           0         1058       1998         0
4   5            7        801           1         2428       2020         0

   BedroomAbvGr  LotArea  SalePrice
0             1     8059     177106
1             4    13530     301044
2             4     9010     360609
3             4    13207     240556
4             1     9117     193656
(300, 10)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Id            300 non-null    int64
 1   OverallQual   300 non-null    int64
 2   GrLivArea     300 non-null    int64
 3   GarageCars    300 non-null    int64
 4   TotalBsmtSF   300 non-null    int64
 5   YearBuilt     300 non-null    int64
 6   FullBath      300 non-null    int64
 7   BedroomAbvGr  300 non-null    int64
 8   LotArea       300 non-null    int64
 9   SalePrice     300 non-null    int64
dtypes: int64(10)
memory usage: 23.6 KB
None

In [6]:
df.describe()

,Id,OverallQual,GrLivArea,GarageCars,TotalBsmtSF,YearBuilt,FullBath,BedroomAbvGr,LotArea,SalePrice
count,300.000000,300.000000,300.000000,300.000000,300.000000,300.000000,300.000000,300.000000,300.000000,300.000000
mean,150.500000,5.326667,2307.386667,1.330000,1468.796667,1986.163333,1.523333,2.926667,8969.453333,252262.903333
std,86.746758,2.873001,1042.561303,1.109898,672.333705,21.377089,1.131543,1.456604,3753.531132,74998.055214
min,1.000000,1.000000,504.000000,0.000000,303.000000,1950.000000,0.000000,1.000000,2009.000000,82494.000000
25%,75.750000,3.000000,1392.250000,0.000000,903.000000,1967.000000,0.000000,2.000000,5996.250000,190355.250000
50%,150.500000,5.000000,2265.500000,1.000000,1502.000000,1986.000000,2.000000,3.000000,9031.000000,251292.500000
75%,225.250000,8.000000,3306.500000,2.000000,2129.500000,2004.250000,3.000000,4.000000,12316.000000,307105.000000
max,300.000000,10.000000,3998.000000,3.000000,2492.000000,2023.000000,3.000000,5.000000,14987.000000,435291.000000

In [7]:
df.isnull().sum()

Id              0
OverallQual     0
GrLivArea       0
GarageCars      0
TotalBsmtSF     0
YearBuilt       0
FullBath        0
BedroomAbvGr    0
LotArea         0
SalePrice       0
dtype: int64

In [12]:
X = df.drop(['SalePrice','Id'],axis=1)
y = df['SalePrice']

In [13]:
X

,OverallQual,GrLivArea,GarageCars,TotalBsmtSF,YearBuilt,FullBath,BedroomAbvGr,LotArea
0,7,1560,0,1658,1969,2,1,8059
1,4,2827,2,1319,2012,3,4,13530
2,8,3920,0,841,2010,1,4,9010
3,5,3044,0,1058,1998,0,4,13207
4,7,801,1,2428,2020,0,1,9117
...,...,...,...,...,...,...,...,...
295,1,3495,1,1792,1954,2,5,4978
296,5,3438,3,1266,2003,0,1,9373
297,6,1992,0,1148,1996,1,1,7907
298,3,3722,1,1407,1998,1,1,8097
299,9,1667,0,988,1958,2,1,14553

In [17]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [18]:
X_train

,OverallQual,GrLivArea,GarageCars,TotalBsmtSF,YearBuilt,FullBath,BedroomAbvGr,LotArea
232,2,1325,0,429,1983,2,2,14135
59,10,899,3,825,2004,0,2,2105
6,3,1106,2,1096,1962,1,4,11153
185,2,3316,2,2352,2021,1,3,11777
173,1,856,1,2208,1998,3,4,2707
...,...,...,...,...,...,...,...,...
188,6,1015,2,900,1964,0,4,9979
71,5,1353,1,2074,1951,1,1,13371
106,3,768,1,2033,1990,2,5,3072
270,4,1228,3,1236,1986,3,5,6437
102,7,3414,0,1176,1986,2,5,11852

In [39]:
model = LinearRegression()
model.fit(X_train,y_train)
y_pred = model.predict(X_test)
y_pred

array([239161.36318913, 190489.66798468, 398000.95746314, 223169.46755225,
       135188.39570786, 180259.03980676, 283708.27101141, 204535.26547718,
       205837.94173062, 171505.33195999, 389527.70178374, 274163.79739932,
       116220.90212357, 171343.53163323, 293879.43188669, 314821.03156748,
       154945.46275533, 146162.96860438, 221221.02813414, 255128.9486496 ,
       235772.5157203 , 167430.5426685 , 208978.16707484, 289813.4757898 ,
       313188.74897607, 382651.91313186, 206610.720434  , 260775.03716678,
       285214.27337024, 443345.98671709, 402224.27697766, 292287.65157278,
       122222.0857363 , 211039.07225072, 291045.64445758, 226581.77285369,
       342146.60151078, 243378.66853477, 235856.80880212, 201521.50903895,
       237379.06138588, 334582.4670175 , 313689.69084594, 292464.38340658,
       376959.34215332, 319400.67913445, 217324.69316316, 256908.21155235,
       218997.8110662 , 332431.87339145, 305659.98833244, 321564.58478164,
       110394.39792686, 304824.1326228 , 202320.80190839, 272444.61942839,
       178702.26077918, 334291.06264612, 292853.7802179 , 139984.44761657])

In [38]:
print("Actul price :",y_test.values)

Actul price : [224163 203881 380236 211664 122139 180067 275810 209025 213952 154885
 395010 253397 115204 189831 300918 314526 135263 135385 222449 250335
 221041 175831 206832 296330 319876 385176 225589 250604 289461 424406
 397482 290763 137842 204186 294974 212206 350830 241072 240319 210194
 215533 318772 294884 302167 353246 310812 212892 263814 226280 309211
 303396 328244 131309 317598 184623 265591 179950 308101 311099 129364]

In [25]:
print("Prediction Price :",y_pred)

Prediction Price : [239161.36318913 190489.66798468 398000.95746314 223169.46755225
 135188.39570786 180259.03980676 283708.27101141 204535.26547718
 205837.94173062 171505.33195999 389527.70178374 274163.79739932
 116220.90212357 171343.53163323 293879.43188669 314821.03156748
 154945.46275533 146162.96860438 221221.02813414 255128.9486496
 235772.5157203  167430.5426685  208978.16707484 289813.4757898
 313188.74897607 382651.91313186 206610.720434   260775.03716678
 285214.27337024 443345.98671709 402224.27697766 292287.65157278
 122222.0857363  211039.07225072 291045.64445758 226581.77285369
 342146.60151078 243378.66853477 235856.80880212 201521.50903895
 237379.06138588 334582.4670175  313689.69084594 292464.38340658
 376959.34215332 319400.67913445 217324.69316316 256908.21155235
 218997.8110662  332431.87339145 305659.98833244 321564.58478164
 110394.39792686 304824.1326228  202320.80190839 272444.61942839
 178702.26077918 334291.06264612 292853.7802179  139984.44761657]

In [30]:
print("Deffrerence of acctule and predicted price :",y_test - y_pred , end=" ")

Deffrerence of acctule and predicted price : 203   -14998.363189
266    13391.332015
152   -17764.957463
9     -11505.467552
233   -13049.395708
226     -192.039807
196    -7898.271011
109     4489.734523
5       8114.058269
175   -16620.331960
237     5482.298216
57    -20766.797399
218    -1016.902124
45     18487.468367
182     7038.568113
221     -295.031567
289   -19682.462755
211   -10777.968604
148     1227.971866
165    -4793.948650
78    -14731.515720
113     8400.457332
249    -2146.167075
250     6516.524210
104     6687.251024
42      2524.086868
281    18978.279566
295   -10171.037167
157     4246.726630
238   -18939.986717
17     -4742.276978
164    -1524.651573
33     15619.914264
24     -6853.072251
215     3928.355542
119   -14375.772854
7       8683.398489
90     -2306.668535
46      4462.191198
73      8672.490961
93    -21846.061386
76    -15810.467017
286   -18805.690846
60      9702.616593
77    -23713.342153
63     -8588.679134
234    -4432.693163
229     6905.788448
111     7282.188934
231   -23220.873391
180    -2263.988332
144     6679.415218
239    20914.602073
75     12773.867377
297   -17697.801908
278    -6853.619428
97      1247.739221
92    -26190.062646
192    18245.219782
25    -10620.447617
Name: SalePrice, dtype: float64

In [31]:
mae = mean_absolute_error(y_test,y_pred)
mse = mean_squared_error(y_test,y_pred)
rmse = np.sqrt(mse)
r2 = r2_score(y_test,y_pred)


print("MAE :", mae)
print("MSE :", mse)
print("RMSE:", rmse)
print("R2  :", r2)

MAE : 10431.655979707542
MSE : 156386511.41905734
RMSE: 12505.459264619487
R2  : 0.9724369952260798

In [33]:
print("Intercept :",model.intercept_)
print("\nCoefficients:")

for column, coefficient in zip(X.columns,model.coef_):
    print(column, ":",coefficient)

Intercept : -1512820.5684315357

Coefficients:
OverallQual : 11914.688135068325
GrLivArea : 55.41025707608751
GarageCars : 19109.6416143307
TotalBsmtSF : 25.199018239899175
YearBuilt : 746.3709783374494
FullBath : 11040.343045740163
BedroomAbvGr : 4812.061994479232
LotArea : -0.1595221079072786

In [36]:
df.head(1)

,Id,OverallQual,GrLivArea,GarageCars,TotalBsmtSF,YearBuilt,FullBath,BedroomAbvGr,LotArea,SalePrice
0,1,7,1560,0,1658,1969,2,1,8059,177106

In [41]:
new_house = pd.DataFrame({
    'OverallQual' : [7],
    'GrLivArea' : [1560], 
    'GarageCars' : [0],
    'TotalBsmtSF' : [1658],
    'YearBuilt': [1969], 
    'FullBath':[2], 
    'BedroomAbvGr':[1], 
    'LotArea': [8059]
})
new_house

,OverallQual,GrLivArea,GarageCars,TotalBsmtSF,YearBuilt,FullBath,BedroomAbvGr,LotArea
0,7,1560,0,1658,1969,2,1,8059

In [43]:
prediction = model.predict(new_house)
print("Predicted House Price :",prediction[0])

Predicted House Price : 194013.8375591645

In [44]:
import pickle
with open("Hose_price_model.pkl","wb") as file:
    pickle.dump(model,file)
print("Model saved successfully")

Model saved successfully

In [45]:
df.head(10)

,Id,OverallQual,GrLivArea,GarageCars,TotalBsmtSF,YearBuilt,FullBath,BedroomAbvGr,LotArea,SalePrice
0,1,7,1560,0,1658,1969,2,1,8059,177106
1,2,4,2827,2,1319,2012,3,4,13530,301044
2,3,8,3920,0,841,2010,1,4,9010,360609
3,4,5,3044,0,1058,1998,0,4,13207,240556
4,5,7,801,1,2428,2020,0,1,9117,193656
5,6,10,680,1,2480,1950,2,1,13081,213952
6,7,3,1106,2,1096,1962,1,4,11153,145539
7,8,7,3670,1,437,2000,2,5,4989,350830
8,9,8,1199,2,1653,2005,1,5,14040,275955
9,10,5,1492,1,2175,2011,1,2,11218,211664

In [47]:
df['OverallQual'].min()

1

In [48]:
df.columns

Index(['Id', 'OverallQual', 'GrLivArea', 'GarageCars', 'TotalBsmtSF',
       'YearBuilt', 'FullBath', 'BedroomAbvGr', 'LotArea', 'SalePrice'],
      dtype='object')

In [50]:
df['GrLivArea'].max()

3998